import cv2
import numpy as np
img = cv2.imread("nam.jpg")
img = cv2.resize(img, (300, 300))
median = cv2.medianBlur(img, 3)
blur = cv2.blur(img, (2, 3))
laplacian = cv2.Laplacian(img, cv2.CV_64FC1)
sobelx = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=5)
sobely = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=5)
kernel = np.random.randint(-5, 5, (3, 3))
dst = cv2.filter2D(img, -1, kernel)
cv2.imshow('Before', img)
cv2.imshow('Median', median)
cv2.imshow('Laplacian', laplacian)
cv2.imshow('Sobelx', sobelx)
cv2.imshow('Sobely', sobely)
cv2.imshow('Blur', blur)
cv2.imshow('Filter2D', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()